import {makeBackup,validateBackup,storeBackup} from './backup.js';
import {textStats,transformText,mediaSize,resize,hex,contrast,jsonFormat,cleanURL,scoreDecision,timerRemaining,validateBookmarks,finite} from './core.js';
const $=id=>document.getElementById(id);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prefix='ms-utility-desk:';
let storageAvailable=true;
function read(name,fallback){try{const raw=localStorage.getItem(prefix+name);return raw?JSON.parse(raw):fallback;}catch{storageAvailable=false;return fallback;}}
function save(name,value){try{localStorage.setItem(prefix+name,JSON.stringify(value));}catch{storageAvailable=false;status('Browser storage is unavailable. Export your work to keep it.');}}
function status(message=''){$('status').textContent=message;}
function safely(fn){try{fn();status();}catch(error){status(error.message);}}
function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Exported. Keep the file somewhere useful.');}
async function copy(value){try{await navigator.clipboard.writeText(value);status('Copied to clipboard.');}catch{status('Clipboard access is unavailable. Select the output and copy it manually.');}}
const tools=[
 {id:'text',name:'Text bench',icon:'Aa',category:'CREATE / WORDS',description:'A little room to write, clean things up, and find the right shape.',note:'Text stays in this tab. Export to keep it.',render:textTool},
 {id:'media',name:'Media math',icon:'▣',category:'CREATE / PRODUCTION',description:'Know the space you need and the dimensions you’re working with.',note:'Calculated locally. Estimates are shown explicitly.',render:mediaTool},
 {id:'color',name:'Color & contrast',icon:'◐',category:'CREATE / DESIGN',description:'Make a pairing feel right—and check whether people can read it.',note:'WCAG 2.2 contrast calculation for solid colors.',render:colorTool},
 {id:'decision',name:'Decision matrix',icon:'⊞',category:'THINK / TRADEOFFS',description:'Make the tradeoffs visible. Your judgment still makes the call.',note:'Your matrix is saved in this browser.',render:decisionTool},
 {id:'focus',name:'Focus session',icon:'◷',category:'DO / ATTENTION',description:'One thing worth doing. A little time set aside for it.',note:'Timer and intention are saved in this browser.',render:focusTool},
 {id:'json',name:'JSON workbench',icon:'{}',category:'BUILD / STRUCTURE',description:'Validate, format, and untangle structured data without uploading it.',note:'JSON stays in this tab. No remote processing.',render:jsonTool},
 {id:'links',name:'Link cleaner',icon:'↗',category:'CURATE / SIGNAL',description:'Keep the destination. Leave the familiar tracking parameters behind.',note:'URLs are parsed locally; the destination is never fetched.',render:linkTool},
 {id:'references',name:'Reference shelf',icon:'≡',category:'CURATE / KNOWLEDGE',description:'A few reliable starting points, with room for your own useful discoveries.',note:'Your added references are saved in this browser.',render:referenceTool},
];
let pins=read('pins',[]);if(!Array.isArray(pins))pins=[];pins=pins.filter(id=>tools.some(t=>t.id===id));
let active=tools.find(t=>t.id===location.hash.slice(1))?.id||'text';
const drafts={text:'',json:'',jsonOutput:'',url:'',urlOutput:'',media:{minutes:'60',mbps:'100',copies:'2',width:'3840',height:'2160',target:'1920'},color:{fg:'#8b2340',bg:'#f4eee6'}};
let history=[];
const defaultDecision={criteria:[{name:'Usefulness',weight:5},{name:'Effort fit',weight:3},{name:'Personal interest',weight:4}],alternatives:[{name:'Option A',scores:[8,5,9]},{name:'Option B',scores:[6,9,7]},{name:'Option C',scores:[9,4,6]}]};
let decision=read('decision',structuredClone(defaultDecision));
try{scoreDecision(decision.criteria,decision.alternatives);if(decision.criteria.some(c=>typeof c.name!=='string')||decision.alternatives.some(a=>typeof a.name!=='string'))throw new Error();}catch{decision=structuredClone(defaultDecision);}
let bookmarks=read('bookmarks',[]);try{bookmarks=validateBookmarks(bookmarks);}catch{bookmarks=[];}
let timer=read('timer',{remaining:1500,running:false,endsAt:0,minutes:25,task:''});
if(!timer||typeof timer.running!=='boolean'||!Number.isFinite(timer.remaining)||timer.remaining<0||timer.remaining>10800||!Number.isFinite(timer.endsAt)||!Number.isFinite(timer.minutes)||timer.minutes<1||timer.minutes>180||typeof timer.task!=='string')timer={remaining:1500,running:false,endsAt:0,minutes:25,task:''};
const content=html=>{$('tool-content').innerHTML=html;};
const metric=(value,label)=>`<div class="metric"><strong>${value}</strong><span>${label}</span></div>`;
function renderNav(){
 const query=$('tool-search').value.trim().toLowerCase();
 const visible=[...tools].sort((a,b)=>Number(pins.includes(b.id))-Number(pins.includes(a.id))).filter(t=>(t.name+' '+t.category+' '+t.description).toLowerCase().includes(query));
 $('tool-nav').innerHTML=(query?'':'<p class="nav-label">THE TOOL SHELF</p>')+visible.map(t=>`<button class="tool-link" data-tool="${t.id}" aria-current="${active===t.id}"><span class="icon" aria-hidden="true">${t.icon}</span><span>${t.name}</span><span class="arrow">${pins.includes(t.id)?'★':'↗'}</span></button>`).join('')+(visible.length?'':'<p class="empty">No tool found. Try “text,” “color,” or “focus.”</p>');
}
function render(){
 const tool=tools.find(t=>t.id===active);renderNav();$('tool-title').textContent=tool.name;$('tool-category').textContent=tool.category;$('tool-description').textContent=tool.description;
 $('tool-number').textContent=String(tools.indexOf(tool)+1).padStart(2,'0');$('storage-note').textContent=storageAvailable?tool.note:'Storage unavailable. Export your work to keep it.';
 $('pin').setAttribute('aria-pressed',String(pins.includes(active)));$('pin').textContent=pins.includes(active)?'★ Pinned':'☆ Pin';status();tool.render();
}
$('tool-nav').addEventListener('click',event=>{const button=event.target.closest('[data-tool]');if(button){active=button.dataset.tool;location.hash=active;render();$('workspace').focus({preventScroll:true});}});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(tools.some(t=>t.id===id)&&id!==active){active=id;render();}});
$('tool-search').addEventListener('input',renderNav);
$('tool-search').addEventListener('keydown',event=>{if(event.key==='Enter')$('tool-nav').querySelector('button')?.click();if(event.key==='Escape'){$('tool-search').value='';renderNav();$('tool-search').blur();}});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)&&!$('about').open){event.preventDefault();$('tool-search').focus();}});
$('pin').addEventListener('click',()=>{pins=pins.includes(active)?pins.filter(id=>id!==active):[...pins,active];save('pins',pins);renderNav();$('pin').setAttribute('aria-pressed',String(pins.includes(active)));$('pin').textContent=pins.includes(active)?'★ Pinned':'☆ Pin';});
$('today').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric'}).format(new Date());
$('help-button').addEventListener('click',()=>$('about').showModal());$('close-help').addEventListener('click',()=>$('about').close());
$('clear-saved').addEventListener('click',()=>{if(!confirm('Clear this desk’s saved pins, matrix, references, and timer? Export anything you want to keep first.'))return;try{for(const key of ['pins','decision','bookmarks','timer'])localStorage.removeItem(prefix+key);}catch{}pins=[];decision=structuredClone(defaultDecision);bookmarks=[];timer={remaining:1500,running:false,endsAt:0,minutes:25,task:''};$('about').close();render();status('Saved desk data cleared.');});
function textTool(){
 content(`<label>Your words<textarea id="words" class="text-area" placeholder="A draft. A caption. A script. Start here…">${esc(drafts.text)}</textarea></label><div class="toolbar"><button data-transform="clean">Clean spacing</button><button data-transform="title">Title Case</button><button data-transform="lower">lowercase</button><button data-transform="upper">UPPERCASE</button><button data-transform="slug">make-a-slug</button><button data-transform="dedupe">Unique lines</button><button id="undo">Undo</button></div><div id="text-metrics" class="metrics"></div><p class="small">Reading estimate: 200 words/minute. Spoken delivery: 130 words/minute. Adjust for your own pace.</p><div class="toolbar"><button class="primary" id="copy-text">Copy text ↗</button><button id="export-text">Export .txt</button><button id="clear-text">Clear</button></div>`);
 const update=()=>{const stats=textStats(drafts.text);$('text-metrics').innerHTML=metric(stats.words,'words')+metric(stats.characters,'characters')+metric(stats.readingMinutes.toFixed(1)+'m','reading estimate')+metric(stats.speakingMinutes.toFixed(1)+'m','speaking estimate');$('undo').disabled=!history.length;};
 $('words').addEventListener('input',()=>{drafts.text=$('words').value;update();});
 $('tool-content').querySelectorAll('[data-transform]').forEach(button=>button.addEventListener('click',()=>{history.push(drafts.text);history=history.slice(-20);drafts.text=transformText(drafts.text,button.dataset.transform);$('words').value=drafts.text;update();}));
 $('undo').onclick=()=>{if(history.length){drafts.text=history.pop();$('words').value=drafts.text;update();}};
 $('copy-text').onclick=()=>copy(drafts.text);$('export-text').onclick=()=>download('words.txt',drafts.text);$('clear-text').onclick=()=>{history.push(drafts.text);drafts.text='';$('words').value='';update();};update();
}
function mediaTool(){
 const d=drafts.media;
 content(`<div class="row three"><label>Duration · minutes<input id="minutes" type="number" min="0" max="1000000" step="any" value="${d.minutes}"></label><label>Bitrate · Mbps<input id="mbps" type="number" min="0" max="1000000" step="any" value="${d.mbps}"></label><label>Number of copies<input id="copies" type="number" min="1" max="100" step="1" value="${d.copies}"></label></div><div class="result-box" id="media-result" aria-live="polite"></div><p class="small">Decimal GB and binary GiB are both shown. Uses constant bitrate; variable bitrate, audio tracks, and container overhead can change the actual file size. Count every backup copy.</p><hr class="split-line"><h3 class="subheading">Keep the proportions</h3><div class="row three"><label>Source width · px<input id="width" type="number" min="1" step="1" value="${d.width}"></label><label>Source height · px<input id="height" type="number" min="1" step="1" value="${d.height}"></label><label>Target width · px<input id="target" type="number" min="1" step="1" value="${d.target}"></label></div><div class="output" id="resize-result" aria-live="polite"></div>`);
 function calculate(){
  const errors=[];
  try{const s=mediaSize(d.minutes,d.mbps,d.copies);if(!Number.isInteger(Number(d.copies)))throw new Error('Copies must be a whole number.');$('media-result').innerHTML=`<span class="big">${s.gb.toLocaleString(undefined,{maximumFractionDigits:2})}</span><span class="unit">GB total</span><p>${s.gib.toFixed(2)} GiB · ${esc(d.copies)} ${Number(d.copies)===1?'copy':'copies'} of ${esc(d.minutes)} minutes at ${esc(d.mbps)} Mbps</p>`;}catch(error){$('media-result').textContent='Enter a valid duration, bitrate, and copy count.';errors.push(error.message);}
  try{const r=resize(d.width,d.height,d.target);$('resize-result').textContent=`${r.width} × ${r.height} px  /  ${r.ratio} aspect ratio  /  ${(r.scale*100).toFixed(1)}% scale`;}catch(error){$('resize-result').textContent='Enter valid whole-number pixel dimensions.';errors.push(error.message);}
  status(errors.join(' '));
 }
 for(const key of Object.keys(d))$(key).addEventListener('input',()=>{d[key]=$(key).value;calculate();});calculate();
}
function colorTool(){
 const d=drafts.color;
 content(`<div class="row"><label>Text color<div class="color-input"><input aria-label="Choose text color" id="fg-picker" type="color" value="${hex(d.fg)}"><input id="fg" value="${esc(d.fg)}" spellcheck="false" maxlength="7" aria-label="Text hex color"></div></label><label>Background color<div class="color-input"><input aria-label="Choose background color" id="bg-picker" type="color" value="${hex(d.bg)}"><input id="bg" value="${esc(d.bg)}" spellcheck="false" maxlength="7" aria-label="Background hex color"></div></label></div><div class="color-preview" id="color-preview"><h3>Rigor can have feeling.</h3><p>Good tools should carry a little personality.<br>And everyone should be able to read them.</p></div><div id="contrast-result" class="result-box" aria-live="polite"></div><div class="toolbar"><button id="swap">Swap colors</button><button class="primary" id="copy-colors">Copy CSS ↗</button></div><p class="small">Large text means at least 24px regular or about 18.7px bold. Passing these ratios checks contrast only, not overall accessibility. <a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html" target="_blank" rel="noreferrer">WCAG guidance ↗</a></p>`);
 function calculate(){safely(()=>{const fg=hex($('fg').value),bg=hex($('bg').value),result=contrast(fg,bg);d.fg=fg;d.bg=bg;$('fg-picker').value=fg;$('bg-picker').value=bg;$('color-preview').style.color=fg;$('color-preview').style.backgroundColor=bg;$('contrast-result').innerHTML=`<span class="big">${result.ratio.toFixed(2)}</span><span class="unit">: 1 contrast ratio</span><div class="verdicts">${[['AA normal text',result.aa],['AA large text',result.aaLarge],['AAA normal text',result.aaa]].map(([label,pass])=>`<span class="verdict ${pass?'pass':'fail'}">${pass?'✓':'×'} ${label}</span>`).join('')}</div>`;});}
 for(const id of ['fg','bg']){$(id).oninput=calculate;$(id+'-picker').oninput=()=>{$(id).value=$(id+'-picker').value;calculate();};}
 $('swap').onclick=()=>{[$('fg').value,$('bg').value]=[$('bg').value,$('fg').value];calculate();};$('copy-colors').onclick=()=>safely(()=>copy(`color: ${hex($('fg').value)};\nbackground-color: ${hex($('bg').value)};`));calculate();
}
function decisionTool(){
 const d=decision;
 content(`<p class="small">Start with the example, then name your own options and criteria. Weight each criterion 0–100; score each option 0–10. Higher always means better, including effort fit.</p><div class="matrix-wrap"><table class="matrix"><thead><tr><th scope="col">Criterion / weight</th>${d.alternatives.map((a,i)=>`<th scope="col"><small>Option ${i+1}</small><input aria-label="Option ${i+1} name" data-option-name="${i}" value="${esc(a.name)}" maxlength="60"><button data-remove-option="${i}" ${d.alternatives.length<=1?'disabled':''} aria-label="Remove option ${i+1}">Remove</button></th>`).join('')}</tr></thead><tbody>${d.criteria.map((c,i)=>`<tr><th scope="row"><input aria-label="Criterion ${i+1} name" data-criterion-name="${i}" value="${esc(c.name)}" maxlength="60"><input aria-label="Criterion ${i+1} weight" data-weight="${i}" type="number" min="0" max="100" value="${c.weight}"><button data-remove-criterion="${i}" ${d.criteria.length<=1?'disabled':''} aria-label="Remove criterion ${i+1}">Remove</button></th>${d.alternatives.map((a,j)=>`<td><input aria-label="Option ${j+1}, criterion ${i+1} score" data-score="${j},${i}" type="number" min="0" max="10" step="0.5" value="${a.scores[i]}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="toolbar"><button id="add-option" ${d.alternatives.length>=6?'disabled':''}>+ Option</button><button id="add-criterion" ${d.criteria.length>=8?'disabled':''}>+ Criterion</button><button id="export-decision">Export matrix</button><button id="reset-decision">Reset example</button></div><h3 class="subheading">What your priorities point toward</h3><div class="ranking" id="ranking" aria-live="polite"></div><p class="small">Score = sum of (weight × rating) ÷ total weight. Close scores are a reason to inspect your assumptions, not outsource your judgment.</p>`);
 function rank(){try{$('ranking').innerHTML=scoreDecision(d.criteria,d.alternatives).map((r,i)=>`<div class="rank-row"><span>${i+1}</span><span class="rank-name" style="--score:${r.score*10}%">${esc(r.name||'Unnamed option')}</span><span class="rank-score">${r.score.toFixed(2)}</span></div>`).join('');status();save('decision',d);}catch(error){$('ranking').textContent='Complete the scores and give at least one criterion a positive weight.';status(error.message);}}
 $('tool-content').querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{const x=input.dataset;if(x.optionName!==undefined)d.alternatives[+x.optionName].name=input.value;else if(x.criterionName!==undefined)d.criteria[+x.criterionName].name=input.value;else if(x.weight!==undefined)d.criteria[+x.weight].weight=input.value===''?'':Number(input.value);else{const [a,c]=x.score.split(',').map(Number);d.alternatives[a].scores[c]=input.value===''?'':Number(input.value);}rank();}));
 $('tool-content').querySelectorAll('[data-remove-option]').forEach(button=>button.onclick=()=>{d.alternatives.splice(+button.dataset.removeOption,1);decisionTool();});
 $('tool-content').querySelectorAll('[data-remove-criterion]').forEach(button=>button.onclick=()=>{const i=+button.dataset.removeCriterion;d.criteria.splice(i,1);d.alternatives.forEach(a=>a.scores.splice(i,1));decisionTool();});
 $('add-option').onclick=()=>{d.alternatives.push({name:`Option ${d.alternatives.length+1}`,scores:d.criteria.map(()=>5)});decisionTool();};
 $('add-criterion').onclick=()=>{d.criteria.push({name:'New criterion',weight:3});d.alternatives.forEach(a=>a.scores.push(5));decisionTool();};
 $('export-decision').onclick=()=>safely(()=>{download('decision-matrix.json',JSON.stringify({criteria:d.criteria,alternatives:d.alternatives,ranking:scoreDecision(d.criteria,d.alternatives)},null,2),'application/json');});
 $('reset-decision').onclick=()=>{if(confirm('Replace this matrix with the example?')){decision=structuredClone(defaultDecision);decisionTool();}};rank();
}
function focusTool(){
 content(`<div class="timer"><label>One thing to move forward<input id="focus-task" maxlength="180" placeholder="What deserves your attention?" value="${esc(timer.task)}"></label><div class="timer-ring"><span class="timer-time" id="timer-time"></span><span class="timer-label" id="timer-label"></span></div><div class="toolbar"><button class="primary" id="timer-toggle"></button><button id="timer-reset">Reset</button></div><label>Session length · minutes<input id="timer-minutes" type="number" min="1" max="180" step="1" value="${timer.minutes}" ${timer.running?'disabled':''}></label></div><p class="small">The countdown uses a finish time, so switching tabs or reloading keeps it accurate. This tab must stay open to show completion; it cannot wake a sleeping device. No notifications or sound permissions needed.</p>`);
 $('focus-task').oninput=()=>{timer.task=$('focus-task').value;save('timer',timer);};
 $('timer-minutes').onchange=()=>safely(()=>{const minutes=finite($('timer-minutes').value,'Session length',1,180);if(!Number.isInteger(minutes))throw new Error('Choose a whole number of minutes.');timer.minutes=minutes;timer.remaining=minutes*60;save('timer',timer);paintTimer();});
 $('timer-toggle').onclick=()=>{if(timer.running){timer.remaining=timerRemaining(timer);timer.running=false;}else{if(!timer.remaining)timer.remaining=timer.minutes*60;timer.endsAt=Date.now()+timer.remaining*1000;timer.running=true;}save('timer',timer);paintTimer();};
 $('timer-reset').onclick=()=>{timer.running=false;timer.remaining=timer.minutes*60;save('timer',timer);paintTimer();};paintTimer();
}
function paintTimer(){
 const remaining=timerRemaining(timer);
 if(active==='focus'&&$('timer-time')){$('timer-time').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timer-label').textContent=timer.running?'A little room to focus':remaining===0?'Session complete':'Ready when you are';$('timer-toggle').textContent=timer.running?'Pause session':'Start session ↗';$('timer-minutes').disabled=timer.running;}
}
setInterval(()=>{if(timer.running&&timerRemaining(timer)===0){timer.running=false;timer.remaining=0;save('timer',timer);status('Focus session complete. Take a breath, then choose what’s next.');}paintTimer();},500);
function jsonTool(){
 content(`<label>Your JSON<textarea id="json-input" class="code" spellcheck="false" placeholder='{"a_small_tool": "a_useful_thing"}'>${esc(drafts.json)}</textarea></label><div class="toolbar"><button class="primary" data-json="pretty">Validate & format ↗</button><button data-json="minify">Minify</button><button data-json="sort">Sort keys</button><button id="json-example">Load example</button></div><label>Output<pre id="json-output" class="output" tabindex="0">${esc(drafts.jsonOutput)}</pre></label><div class="toolbar"><button id="copy-json">Copy output</button><button id="export-json">Export .json</button></div><p class="small">Standard JSON only, up to 1 MB. Sorting keeps array order intact. JavaScript numbers may lose precision beyond ±9,007,199,254,740,991; represent large identifiers as strings.</p>`);
 $('json-input').oninput=()=>{drafts.json=$('json-input').value;};
 $('tool-content').querySelectorAll('[data-json]').forEach(button=>button.onclick=()=>{try{drafts.jsonOutput=jsonFormat(drafts.json,button.dataset.json);$('json-output').textContent=drafts.jsonOutput;status('Valid JSON. Output is ready.');}catch(error){drafts.jsonOutput='';$('json-output').textContent='';status('Invalid JSON: '+error.message);}});
 $('json-example').onclick=()=>{drafts.json='{"purpose":"Make useful things","lanes":["creation","curation","expression"],"version":1}';$('json-input').value=drafts.json;};
 $('copy-json').onclick=()=>copy(drafts.jsonOutput);$('export-json').onclick=()=>{if(!drafts.jsonOutput){status('Format valid JSON before exporting.');return;}download('formatted.json',drafts.jsonOutput,'application/json');};
}
function linkTool(){
 content(`<label>Link to clean<textarea id="url-input" rows="4" placeholder="https://example.com/article?utm_source=newsletter&id=8">${esc(drafts.url)}</textarea></label><div class="toolbar"><button class="primary" id="clean-link">Clean the link ↗</button><button id="link-example">Try an example</button></div><label>Cleaned link<pre class="output" id="url-output" tabindex="0">${esc(drafts.urlOutput)}</pre></label><p id="removed" class="small"></p><div class="toolbar"><button id="copy-link">Copy clean link</button></div><p class="small">Removes utm_* parameters and known click identifiers (fbclid, gclid, dclid, msclkid, mc_cid, mc_eid, igshid). Other parameters and fragments stay intact. This does not remove tracking embedded in short links or page content.</p>`);
 $('url-input').oninput=()=>{drafts.url=$('url-input').value;};
 $('clean-link').onclick=()=>{try{const result=cleanURL(drafts.url.trim());drafts.urlOutput=result.url;$('url-output').textContent=result.url;$('removed').textContent=result.removed.length?'Removed: '+result.removed.join(', '):'No recognized tracking parameters found.';status('Ready to share.');}catch(error){drafts.urlOutput='';$('url-output').textContent='';$('removed').textContent='';status(error.message);}};
 $('link-example').onclick=()=>{drafts.url='https://example.com/creative-work?id=8&utm_source=newsletter&utm_medium=email#notes';$('url-input').value=drafts.url;};$('copy-link').onclick=()=>copy(drafts.urlOutput);
}
const references=[
 {title:'MDN Web Docs',url:'https://developer.mozilla.org/en-US/docs/Web',note:'The mechanics of the web: HTML, CSS, JavaScript, and browser APIs.',category:'Computational systems'},
 {title:'FFmpeg documentation',url:'https://ffmpeg.org/documentation.html',note:'Formats, codecs, filters, and the machinery behind media workflows.',category:'Creative production'},
 {title:'W3C accessibility tutorials',url:'https://www.w3.org/WAI/tutorials/',note:'Practical patterns for interfaces more people can use.',category:'Product & UX'},
 {title:'Stanford Encyclopedia of Philosophy',url:'https://plato.stanford.edu/',note:'Substantial, authored entries when a concept deserves more than a summary.',category:'Philosophy & meaning'},
 {title:'Pro Git',url:'https://git-scm.com/book/en/v2',note:'Version control, explained from the foundations upward.',category:'Systems & practice'},
 {title:'OBS knowledge base',url:'https://obsproject.com/kb/',note:'Capture, audio, scenes, and the practical side of a broadcast.',category:'Creative production'},
];
function referenceTool(){
 content(`<label>Search the shelf<input id="reference-search" type="search" placeholder="A title, topic, or note…"></label><div class="references" id="reference-list"></div><details><summary>Add something useful</summary><form id="reference-form"><div class="row" style="margin-top:20px"><label>Title<input id="reference-title" maxlength="100" required></label><label>URL<input id="reference-url" type="url" required placeholder="https://"></label></div><label>Why keep it?<input id="reference-note" maxlength="300"></label><div class="toolbar"><button class="primary" type="submit">Add to my shelf ↗</button></div></form></details><div class="toolbar"><button id="export-references">Export my references</button><label class="file-label"><span>Import references</span><input id="import-references" type="file" accept=".json,application/json"></label></div><p class="small">The starter shelf is a set of reference sources, not a claim about your personal favorites. Your additions stay local and can be exported.</p>`);
 function list(){const query=$('reference-search').value.toLowerCase();const all=[...bookmarks.map((r,i)=>({...r,category:'Your shelf',index:i})),...references].filter(r=>(r.title+' '+r.note+' '+r.category).toLowerCase().includes(query));$('reference-list').innerHTML=all.map(r=>`<article class="reference"><span class="reference-tag">${esc(r.category)}</span><a href="${esc(r.url)}" target="_blank" rel="noreferrer">${esc(r.title)} ↗</a><p>${esc(r.note)}</p>${r.index!==undefined?`<button class="remove" data-remove-reference="${r.index}" aria-label="Remove ${esc(r.title)}">×</button>`:''}</article>`).join('')||(query?'<p class="empty">No references match that search.</p>':'');$('reference-list').querySelectorAll('[data-remove-reference]').forEach(button=>button.onclick=()=>{bookmarks.splice(+button.dataset.removeReference,1);save('bookmarks',bookmarks);list();});}
 $('reference-search').oninput=list;
 $('reference-form').onsubmit=event=>{event.preventDefault();try{const [item]=validateBookmarks([{title:$('reference-title').value,url:$('reference-url').value,note:$('reference-note').value}]);if(bookmarks.length>=100)throw new Error('The shelf holds up to 100 personal references.');if(bookmarks.some(b=>b.url===item.url))throw new Error('That link is already on your shelf.');bookmarks.push(item);save('bookmarks',bookmarks);$('reference-form').reset();list();status('Added to your shelf.');}catch(error){status(error.message);}};
 $('export-references').onclick=()=>download('my-reference-shelf.json',JSON.stringify(bookmarks,null,2),'application/json');
 $('import-references').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>200000)throw new Error('Use a reference file smaller than 200 KB.');const items=validateBookmarks(JSON.parse(await file.text()));if(bookmarks.length&&!confirm('Replace your added references with this file?'))return;bookmarks=items;save('bookmarks',bookmarks);list();status('References imported.');}catch(error){status('Import failed: '+error.message);}finally{event.target.value='';}};list();
}
render();

$('backup-desk').onclick=()=>{try{download('michael-utility-desk.json',JSON.stringify(makeBackup({pins,decision,bookmarks,timer}),null,2),'application/json');$('backup-status').textContent='Backup exported. It includes saved tools and a paused copy of your timer. Text and JSON drafts are excluded.';}catch(error){$('backup-status').textContent=error.message;}};
$('restore-desk').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1_000_000)throw new Error('Choose a backup smaller than 1 MB.');const data=validateBackup(JSON.parse(await file.text()));if(!confirm(`Restore ${data.bookmarks.length} references, ${data.decision.alternatives.length} decision options and ${data.pins.length} pins? This replaces saved desk data. Export a backup first to keep the current desk.`))return;storeBackup(localStorage,data);({pins,decision,bookmarks,timer}=data);storageAvailable=true;render();$('backup-status').textContent='Desk restored. Your focus timer is paused and ready when you are.';}catch(error){$('backup-status').textContent=error.message;}finally{event.target.value='';}};
